### ISSUE TITLE
Use ShinyAngelGFX graphics with the Arc Furnace

### ISSUE THREAD

**Issue by Tixout31** [LennyIndustries/Lenny-Industries#15]
Hey,
Sorry to open an "Issue" to make a suggestion, but that is the only I know to reach you. I am not aware about issue flaring, and if I would be able to flag it as suggestion.
Anyways, i would like to know if it would be possible for you to use ShinyAngelGFX graphics whenever the mod is installed.

I am not sure if you the graphic's author authorization or anything. I am currently trying to patch it myself in local but it would be a great addition as their graphics allow easy differentiation between the different tiers of blast furnaces.

Thanks a lot ! :)

**Comment by Tixout31** [comment]
Alright,

So i did manage to make it work only by replace the path of graphics (Icons and Animations). However ShinyAngelGFX uses a local functions for the fluids boxes management (with pipe shadow, and graphical layers that i don't understand fully). So i had to copy their code to make it work. I am not aware if their function would be callable from your mod. (I suck at function scope in lua).

**Comment by LennyIndustries** [comment]
I currently don't have much time, but I'll look into it more after the holidays.

**Comment by LennyIndustries** [comment]
ShinyAngelGFX support has been added in the new version, 1.1.8.
